export { default as StudentProfile } from './StudentProfile';
export { default as TeacherProfile } from './TeacherProfile';
export { default as Report } from './Report';
export { default as Attendance } from './Attendance';
export { default as TeacherDashboard } from './TeacherDashboard';
export { default as StudentDashboard } from './StudentDashboard';
export { default as SemReports } from './SemReports';
export { default as UpdateAttendance } from './UpdateAttendance';
export { default as UpdateMarks } from './UpdateMarks';
